server.port=8080

spring.application.name=ticketapp8

spring.datasource.password=${DB_PASSWORD}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-53nfz4utjol8ovyp.us.auth0.com/

# Expose actuator endpoints
management.endpoints.web.exposure.include=*

# Show health details
management.endpoint.health.show-details=always

# Application information
management.info.env.enabled=true

info.app.name=Ticket Management API
info.app.version=1.0
info.app.description=Spring Boot REST API for Ticket Management
info.app.author=Chetan Kumar Bagaria